name: Build Docker Image Ubuntu 12.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: cd ubuntu-docker/1204 && make build

    - name: Change directory permissions
      run: chmod 777 ubuntu-docker/1204

    - name: Run example in container
      run: cd ubuntu-docker/1204 && make test

    - name: Publish to Dockerhub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: cd ubuntu-docker/1204 && make publish
