name: Build Docker Image Ubuntu 14.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ubuntu-docker/1404/Dockerfile --tag ubuntu-1404:$(date +%s)

    - name: run example in container
      run: cd ubuntu-docker/1404 && docker run -it -v $PWD/mnt nmag nsim sphere1.py
  
