name: Build Docker Image Ubuntu 12.04

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ubuntu-docker/1204 && make build
      #run: docker build . --file ubuntu-docker/1204/Dockerfile --tag ubuntu-1204:$(date +%s)

    - name: change directory permissions
      run: chmod 777 ubuntu-docker/1204

    - name: run example in container
      run: cd ubuntu-docker/1204 && make test
  
